[project]
enable_telemetry = false
session_timeout = 3600
user_session_timeout = 1296000
cache = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
auto_tag_thread = true
edit_message = true

[features.audio]
enabled = true
min_decibels = -45
initial_silence_timeout = 3000
silence_timeout = 1500
max_duration = 15000
chunk_duration = 1000
sample_rate = 44100

[features.spontaneous_file_upload]
enabled = true
max_files = 5
max_size_mb = 20

[UI]
name = "Nikki"
description = "Nikki AiA your personal Ai Assistant"
default_theme = "dark"
layout = "default"
cot = "full"
custom_css = "/public/nikki.css"
custom_js = "/public/nikki.js"

[[UI.header_links]]
    name = "Integrations"
    display_name = "Integrations"
    icon_url = "/public/plug.svg"
    url = "/integrations"
    target = "_self"

[[UI.header_links]]
    name = "Schedules"
    display_name = "Schedules"
    icon_url = "/public/clock.svg"
    url = "/schedules"
    target = "_self"

[meta]
generated_by = "2.12.0"
